/*
 * File: app/view/main/Toolbar.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.main.Toolbar', {
    extend: 'Ext.Toolbar',
    alias: 'widget.maintoolbar',

    requires: [
        'Ext.Component'
    ],

    docked: 'top',

    items: [
        {
            xtype: 'component',
            reference: 'logo',
            userCls: 'main-logo',
            html: 'Sencha'
        }
    ]

});